# Generated by Django 5.0.7 on 2024-08-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
